Args = --initialize-at-build-time=\
org.slf4j,\
io.vertx.core.impl.launcher.commands,\
io.vertx.core.Starter,\
io.vertx.core.VertxOptions,\
com.google.zxing

Args = --initialize-at-run-time=\
io.netty.handler.codec.compression.BrotliDecoder,\
io.netty.handler.codec.compression.BrotliEncoder,\
io.netty.handler.ssl.ReferenceCountedOpenSslEngine,\
io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator,\
io.netty.handler.ssl.ConscryptAlpnSslEngine

Args = -H:ReflectionConfigurationFiles=${.}/reflect-config.json
Args = -H:ResourceConfigurationFiles=${.}/resource-config.json
Args = -H:JNIConfigurationFiles=${.}/jni-config.json
Args = -H:DynamicProxyConfigurationFiles=${.}/proxy-config.json

Args = -H:+AddAllCharsets
Args = --enable-http
Args = --enable-https
Args = --enable-all-security-services
